/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MyBook Z Series
 */
public class CekNomorGenapGanjilFrame extends javax.swing.JFrame {

    /**
     * Creates new form CekNomorGenapGanjilFrame
     */
    public CekNomorGenapGanjilFrame() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jOptionPaneError = new javax.swing.JOptionPane();
        jOptionPaneHasil = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldAngka = new javax.swing.JTextField();
        buttonCek = new javax.swing.JButton();

        jOptionPaneError.setBackground(new java.awt.Color(255, 102, 102));

        jOptionPaneHasil.setBackground(new java.awt.Color(204, 255, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Cek Nomor Genap Ganjil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Masukan Angka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        fieldAngka.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldAngkaFocusGained(evt);
            }
        });
        fieldAngka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldAngkaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        jPanel1.add(fieldAngka, gridBagConstraints);

        buttonCek.setText("Cek");
        buttonCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 10, 10);
        jPanel1.add(buttonCek, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAngkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldAngkaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_fieldAngkaKeyTyped

    private void buttonCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekActionPerformed
        try {
            // Mengambil input angka dari fieldAngka
            String input = fieldAngka.getText();
            int angka = Integer.parseInt(input);

            // Menentukan apakah angka genap atau ganjil
            String genapGanjil;
            if (angka % 2 == 0) {
                genapGanjil = "Genap";
            } else {
                genapGanjil = "Ganjil";
            }

            // Memeriksa apakah angka prima
            String prima;
            if (isPrima(angka)) {
                prima = "prima";
            } else {
                prima = "bukan prima";
            }

            // Menampilkan hasil
            jOptionPaneHasil.showMessageDialog(null, 
                    "Angka: " + angka + "\n" +
                    "Jenis: " + genapGanjil + "\n" +
                    "Status: " + prima,
                    "Hasil", jOptionPaneHasil.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            // Menangani error jika input bukan angka
            jOptionPaneError.showMessageDialog(null,
                    "Input tidak valid!.",
                    "Error", jOptionPaneError.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCekActionPerformed

    private void fieldAngkaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldAngkaFocusGained
        fieldAngka.setText("");
    }//GEN-LAST:event_fieldAngkaFocusGained

    // Fungsi untuk memeriksa apakah suatu angka prima
    public static boolean isPrima(int angka) {
        if (angka <= 1) return false; // Bilangan kurang dari 2 bukan prima
        for (int i = 2; i <= Math.sqrt(angka); i++) {
            if (angka % i == 0) {
                return false; // Jika dapat dibagi, berarti bukan prima
            }
        }
        return true; // Jika tidak ada pembagi selain 1 dan angka itu sendiri
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekNomorGenapGanjilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekNomorGenapGanjilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekNomorGenapGanjilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekNomorGenapGanjilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekNomorGenapGanjilFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCek;
    private javax.swing.JTextField fieldAngka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPaneError;
    private javax.swing.JOptionPane jOptionPaneHasil;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
